# Generated by Django 4.0.2 on 2022-02-17 09:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('psychiatrists', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='psychiatrist',
            name='available_times',
            field=models.TextField(blank=True, max_length=100, null=True),
        ),
    ]
