# Generated by Django 4.0.2 on 2022-02-19 14:57

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Person',
            fields=[
                ('username', models.CharField(max_length=200, primary_key=True, serialize=False)),
                ('name', models.CharField(default='Unknown', max_length=200)),
                ('password', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=50)),
                ('joined_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('date_of_birth', models.DateTimeField(default=django.utils.timezone.now)),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female')], default='F', max_length=1)),
                ('mobile_number', models.CharField(blank=True, max_length=50, null=True)),
            ],
        ),
    ]
