# Generated by Django 4.0.2 on 2022-02-17 18:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('persons', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='username',
            field=models.CharField(default='Unknown', max_length=200),
        ),
    ]
