# Generated by Django 4.0.2 on 2022-02-19 14:57

import datetime
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('psychiatrists', '0001_initial'),
        ('patients', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('response', models.CharField(default='unspecified', max_length=20)),
                ('score', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Option',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, parent_link=True, to='take_questionnaire.question')),
                ('text', models.CharField(default='unspecified', max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('RD', 'Radio'), ('SL', 'Number Slider'), ('CH', 'Multiple Choice')], default='RD', max_length=2)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('changed_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('question_text', models.CharField(default='unspecified', max_length=1000)),
                ('added_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='psychiatrists.psychiatrist')),
            ],
        ),
        migrations.CreateModel(
            name='Test',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, verbose_name='Name of the test')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('is_approved', models.CharField(choices=[('P_AP', 'Pending Approval'), ('USE', 'Being Used'), ('P_DP', 'Pending Removal'), ('ARC', 'Archived')], default='P_AP', max_length=5)),
                ('added_by', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='psychiatrists.psychiatrist')),
            ],
        ),
        migrations.CreateModel(
            name='TestResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('submission_time', models.DateTimeField(default=django.utils.timezone.now)),
                ('comment', models.TextField(default='')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='patients.patient')),
                ('questions', models.ManyToManyField(through='take_questionnaire.Answer', to='take_questionnaire.Question')),
                ('test', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='take_questionnaire.test')),
                ('verifier', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='psychiatrists.psychiatrist')),
            ],
        ),
        migrations.CreateModel(
            name='TestQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_pending', models.CharField(choices=[('P_AP', 'Pending Approval'), ('USE', 'Being Used'), ('P_DP', 'Pending Removal'), ('ARC', 'Archived')], default='P_AP', max_length=5, verbose_name='the relation between test and the qeustion')),
                ('question_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='take_questionnaire.question')),
                ('test_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='take_questionnaire.test')),
            ],
        ),
        migrations.AddField(
            model_name='test',
            name='questions',
            field=models.ManyToManyField(through='take_questionnaire.TestQuestion', to='take_questionnaire.Question'),
        ),
        migrations.CreateModel(
            name='Rule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rubric_score', models.IntegerField(default=0)),
                ('_from', models.DateTimeField(default=django.utils.timezone.now)),
                ('_end', models.DateTimeField(default=datetime.datetime(9999, 12, 31, 23, 59, 59, 999999))),
                ('option_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='take_questionnaire.option')),
                ('question_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='take_questionnaire.question')),
            ],
        ),
        migrations.AddField(
            model_name='answer',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='take_questionnaire.question'),
        ),
        migrations.AddField(
            model_name='answer',
            name='testresult',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='take_questionnaire.testresult'),
        ),
    ]
