# Generated by Django 4.0.2 on 2022-02-17 06:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.CharField(max_length=15, primary_key=True, serialize=False, verbose_name='unique id to every question')),
                ('type', models.CharField(default='unspecified', max_length=20)),
            ],
        ),
    ]
