# Generated by Django 4.0.2 on 2022-02-17 09:09

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('psychiatrists', '0002_alter_psychiatrist_available_times'),
        ('take_questionnaire', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Option',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(default='unspecified', max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Test',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, verbose_name='Name of the test')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('is_approved', models.CharField(choices=[('P_AP', 'Pending Approval'), ('USE', 'Being Used'), ('P_DP', 'Pending Removal'), ('ARC', 'Archived')], default='P_AP', max_length=5)),
                ('added_by', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='psychiatrists.psychiatrist')),
            ],
        ),
        migrations.AddField(
            model_name='question',
            name='added_by',
            field=models.ForeignKey(default='hehe', on_delete=django.db.models.deletion.DO_NOTHING, to='psychiatrists.psychiatrist'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='question',
            name='changed_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='question',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='question',
            name='question_text',
            field=models.CharField(default='unspecified', max_length=1000),
        ),
        migrations.AlterField(
            model_name='question',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='question',
            name='type',
            field=models.CharField(choices=[('RD', 'Radio'), ('SL', 'Number Slider'), ('CH', 'Multiple Choice')], default='RD', max_length=2),
        ),
        migrations.CreateModel(
            name='TestQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_pending', models.CharField(choices=[('P_AP', 'Pending Approval'), ('USE', 'Being Used'), ('P_DP', 'Pending Removal'), ('ARC', 'Archived')], default='P_AP', max_length=5, verbose_name='the relation between test and the qeustion')),
                ('question_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='take_questionnaire.question')),
                ('test_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='take_questionnaire.test')),
            ],
        ),
        migrations.AddField(
            model_name='test',
            name='questions',
            field=models.ManyToManyField(through='take_questionnaire.TestQuestion', to='take_questionnaire.Question'),
        ),
        migrations.CreateModel(
            name='Rule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rubric_score', models.FloatField(default=0)),
                ('_from', models.DateTimeField(default=django.utils.timezone.now)),
                ('_end', models.DateTimeField(default=django.utils.timezone.now)),
                ('option_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='take_questionnaire.option')),
                ('question_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='take_questionnaire.question')),
            ],
        ),
        migrations.AddField(
            model_name='option',
            name='question_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='take_questionnaire.question'),
        ),
    ]
