# Generated by Django 4.0.2 on 2022-02-17 19:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('take_questionnaire', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='answer',
            old_name='qestion',
            new_name='question',
        ),
    ]
