# Generated by Django 4.0.2 on 2022-02-17 07:45

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('take_questionnaire', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='question',
            name='type',
            field=models.CharField(choices=[('RD', 'Radio'), ('SL', 'Number Slider'), ('CH', 'Multiple Choice')],
                                   default='RD', max_length=2),
        ),
    ]
