# Generated by Django 4.0.2 on 2022-02-16 16:34

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('take_questionnaire', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='type',
            field=models.CharField(default='unspecified', max_length=20),
        ),
    ]
