# Generated by Django 4.0.2 on 2022-02-19 13:09

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('take_questionnaire', '0002_alter_question_added_by'),
    ]

    operations = [
        migrations.AlterField(
            model_name='option',
            name='question_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, parent_link=True, to='take_questionnaire.question'),
        ),
        migrations.AlterField(
            model_name='rule',
            name='_end',
            field=models.DateTimeField(default=datetime.datetime(9999, 12, 31, 23, 59, 59, 999999)),
        ),
        migrations.AlterField(
            model_name='testresult',
            name='comment',
            field=models.TextField(default=''),
        ),
    ]
