# Generated by Django 4.0.2 on 2022-02-17 09:32

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0001_initial'),
        ('psychiatrists', '0002_alter_psychiatrist_available_times'),
        ('take_questionnaire', '0002_option_test_question_added_by_question_changed_at_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('response', models.CharField(default='unspecified', max_length=20)),
                ('score', models.IntegerField(default=0)),
                ('qestion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='take_questionnaire.question')),
            ],
        ),
        migrations.CreateModel(
            name='TestResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('submission_time', models.DateTimeField(default=django.utils.timezone.now)),
                ('comment', models.TextField()),
                ('answers', models.ManyToManyField(through='take_questionnaire.Answer', to='take_questionnaire.Question')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='patients.patient')),
                ('test', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='take_questionnaire.test')),
                ('verifier', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='psychiatrists.psychiatrist')),
            ],
        ),
        migrations.AddField(
            model_name='answer',
            name='testresult',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='take_questionnaire.testresult'),
        ),
    ]
