# Generated by Django 4.0.2 on 2022-02-19 17:20

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('psychiatrists', '0001_initial'),
        ('take_questionnaire', '0002_alter_answer_response'),
    ]

    operations = [
        migrations.CreateModel(
            name='Dieases',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, verbose_name='Name of the disease')),
                ('description', models.TextField(max_length=1000, verbose_name='Description of the disease')),
                ('creation_time', models.DateTimeField(default=django.utils.timezone.now)),
                ('reviewer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='psychiatrists.psychiatrist')),
            ],
        ),
        migrations.AddField(
            model_name='testresult',
            name='dieaseses',
            field=models.ManyToManyField(to='take_questionnaire.Dieases'),
        ),
    ]
