# Generated by Django 4.0.2 on 2022-02-17 08:26

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('take_questionnaire', '0002_alter_question_id_alter_question_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='changed_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='question',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='question',
            name='question_text',
            field=models.CharField(default='unspecified', max_length=1000),
        ),
    ]
