# Generated by Django 4.0.2 on 2022-02-17 05:20

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('take_questionnaire', '0003_alter_question_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
