# Generated by Django 4.0.2 on 2022-02-19 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('take_questionnaire', '0003_dieases_testresult_dieaseses'),
    ]

    operations = [
        migrations.AddField(
            model_name='test',
            name='details_duration',
            field=models.CharField(default='unspecified', max_length=1000),
        ),
        migrations.AddField(
            model_name='test',
            name='details_gimmic',
            field=models.CharField(default='unspecified', max_length=1000),
        ),
        migrations.AddField(
            model_name='test',
            name='instruction',
            field=models.CharField(default='unspecified', max_length=1000),
        ),
    ]
