# Generated by Django 4.0.2 on 2022-02-17 09:24

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('psychiatrists', '0002_alter_psychiatrist_available_times'),
        ('take_questionnaire', '0003_question_changed_at_question_created_at_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Option',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(default='unspecified', max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Test',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, verbose_name='Name of the test')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('is_approved', models.CharField(
                    choices=[('P_AP', 'Pending Approval'), ('USE', 'Being Used'), ('P_DP', 'Pending Removal'),
                             ('ARC', 'Archived')], default='P_AP', max_length=5)),
                ('added_by',
                 models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='psychiatrists.psychiatrist')),
            ],
        ),
        migrations.AddField(
            model_name='question',
            name='added_by',
            field=models.ForeignKey(default='unspecified', on_delete=django.db.models.deletion.DO_NOTHING,
                                    to='psychiatrists.psychiatrist'),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='TestQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_pending', models.CharField(
                    choices=[('P_AP', 'Pending Approval'), ('USE', 'Being Used'), ('P_DP', 'Pending Removal'),
                             ('ARC', 'Archived')], default='P_AP', max_length=5,
                    verbose_name='the relation between test and the qeustion')),
                ('question_id',
                 models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='take_questionnaire.question')),
                ('test_id',
                 models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='take_questionnaire.test')),
            ],
        ),
        migrations.CreateModel(
            name='Rule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rubric_score', models.FloatField(default=0)),
                ('_from', models.DateTimeField(default=django.utils.timezone.now)),
                ('_end', models.DateTimeField(default=django.utils.timezone.now)),
                ('option_id',
                 models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='take_questionnaire.option')),
                ('question_id',
                 models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='take_questionnaire.question')),
            ],
        ),
        migrations.AddField(
            model_name='option',
            name='question_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='take_questionnaire.question'),
        ),
    ]
