# Generated by Django 4.0.2 on 2022-02-19 18:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('psychiatrists', '0001_initial'),
        ('take_questionnaire', '0004_test_details_duration_test_details_gimmic_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='testresult',
            name='consultations',
            field=models.ManyToManyField(to='psychiatrists.Psychiatrist'),
        ),
        migrations.AlterField(
            model_name='testresult',
            name='verifier',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='verified_testresult', to='psychiatrists.psychiatrist'),
        ),
    ]
