# Generated by Django 4.0.2 on 2022-02-19 19:37

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('psychiatrists', '0001_initial'),
        ('take_questionnaire', '0005_testresult_consultations_alter_testresult_verifier'),
    ]

    operations = [
        migrations.AddField(
            model_name='testresult',
            name='verification_time',
            field=models.DateTimeField(default=datetime.datetime(9999, 12, 31, 23, 59, 59, 999999)),
        ),
        migrations.AlterField(
            model_name='testresult',
            name='verifier',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='verified_testresult', to='psychiatrists.psychiatrist'),
        ),
    ]
