# Generated by Django 4.0.2 on 2022-02-19 19:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('take_questionnaire', '0006_testresult_verification_time_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='test',
            name='has_score',
            field=models.BooleanField(default=False),
        ),
    ]
