# Generated by Django 4.0.2 on 2022-02-19 20:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('take_questionnaire', '0007_test_has_score'),
    ]

    operations = [
        migrations.AlterField(
            model_name='testresult',
            name='verification_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
