# Generated by Django 4.0.2 on 2022-02-20 03:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('take_questionnaire', '0008_alter_testresult_verification_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='testresult',
            name='comment',
            field=models.TextField(blank=True, default='', null=True),
        ),
    ]
