# Generated by Django 4.0.2 on 2022-02-17 20:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('persons', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('person_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='persons.person')),
                ('height', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='height in cm')),
                ('weight', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='weight in kg')),
                ('location', models.CharField(blank=True, max_length=200, null=True, verbose_name='location')),
                ('info', models.CharField(blank=True, max_length=200, null=True, verbose_name='info')),
            ],
            bases=('persons.person',),
        ),
    ]
